[project]
name = "pdf2md"
version = "0.1.0"
description = "Transformar PDF em Markdown com qualidade e eficiÃªncia"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "diskcache>=5.6.3",
    "docling[vlm]>=2.63.0",
    "pymupdf>=1.26.6",
    "rich>=14.2.0",
]
